"""
Django settings for systraker project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rx72xk-8vgf@3%(_vj^h4xse!ygvvh@bvaxd3(gf!jhz=z9nzq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [".trycloudflare.com","app.montacargasamym.com","127.0.0.1","localhost",]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'index',
    'dashboard',
    'import_export',
    'axes', 
    'requerimientos', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
    
]



ROOT_URLCONF = 'systraker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'systraker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# aqui va la base de datos 
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'NEW_SYSTRAKER',
        'HOST': 'SQLSERVER', 
        'USER': 'desarrollo',
        'PASSWORD': '4ndr3$-31',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'Encrypt=no;TrustServerCertificate=yes;'
            
        },
    },
    
    'requerimientos': {
        'ENGINE': 'mssql',
        'NAME': 'PB_REQUERIMIENTOS',
        'HOST': 'SQLSERVER', 
        'USER': 'desarrollo',
        'PASSWORD': '4ndr3$-31',
        'PORT': '1433',
        'OPTIONS': {'driver': 'ODBC Driver 18 for SQL Server',
                    'extra_params': 'Encrypt=no;TrustServerCertificate=yes;'
                    
        
        },
    },
    
    
}

# Router de bases de datos

DATABASE_ROUTERS = [
    'requerimientos.routers.RequerimientosRouter',
]

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


STATIC_URL = '/SYSTRACK/index/static'
STATIC_ROOT = r'E:\inetpub\wwwroot\PRUEBAS\SYSTRACK\index\static'
#STATIC_URL = '/static/'



# Sesión dura 8 horas (jornada laboral)
SESSION_COOKIE_AGE = 28800

# Se renueva el contador con cada request — mientras uses el sistema no expira
SESSION_SAVE_EVERY_REQUEST = True

# Solo expira si cierras el navegador O si pasas 8 horas sin hacer nada
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# AXES igual está bien, solo ajusta el mensaje
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 0.25
AXES_LOCKOUT_CALLABLE = None


AXES_USERNAME_CALLABLE = None          # No usar función personalizada para obtener el usuario
AXES_LOCK_OUT_AT_FAILURE = True        # Bloquear cuenta al alcanzar el límite de intentos
AXES_LOCKOUT_PARAMETERS = ["username"] # Bloquear solo por nombre de usuario, no por IP


AXES_ENABLED = False


#ESTE ES LA CONFICURACION DE CLOUDFLARE
CSRF_TRUSTED_ORIGINS = [
    "https://*.trycloudflare.com",
]


# Importante — agrega esto también:
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') # le dice a Django que confíe en que la conexión es HTTPS aunque él internamente esté corriendo en HTTP.




#CONFIGURACION DEL CORREO 

import os

EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST          = 'smtp.office365.com'
EMAIL_PORT          = 587
EMAIL_USE_TLS       = True
EMAIL_HOST_USER     = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL  = os.getenv('DEFAULT_FROM_EMAIL')
print("DEBUG DEFAULT_FROM_EMAIL =", repr(DEFAULT_FROM_EMAIL))

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'requerimientos': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}