# Generated by Django 6.0.4 on 2026-05-23 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacenamiento',
            fields=[
                ('g219_id', models.AutoField(primary_key=True, serialize=False)),
                ('g219_almacenamiento', models.CharField(max_length=100)),
                ('g219_estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'j219_almacenamiento',
            },
        ),
        migrations.CreateModel(
            name='Antivirus',
            fields=[
                ('g208_id', models.AutoField(primary_key=True, serialize=False)),
                ('g208_antivirus', models.CharField(max_length=100)),
                ('g208_estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'j208_antivirus',
            },
        ),
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('g207_id', models.AutoField(primary_key=True, serialize=False)),
                ('g207_co', models.CharField(max_length=20, unique=True)),
                ('g207_descripcion_co', models.CharField(max_length=150)),
                ('g207_estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'j207_centrocosto',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('g204_id', models.AutoField(primary_key=True, serialize=False)),
                ('g204_departamento', models.CharField(max_length=100)),
                ('g204_estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'j204_departamento',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('g201_id', models.AutoField(primary_key=True, serialize=False)),
                ('g201_descripcion', models.CharField(max_length=100)),
                ('g201_estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'j201_estado',
            },
        ),
        migrations.CreateModel(
            name='LicenciaOffice',
            fields=[
                ('g211_id', models.AutoField(primary_key=True, serialize=False)),
                ('g211_office', models.CharField(max_length=100)),
                ('g211_estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'j211_licenciaoffice',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('g202_id', models.AutoField(primary_key=True, serialize=False)),
                ('g202_marca', models.CharField(max_length=100)),
                ('g202_estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'j202_marca',
            },
        ),
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('g218_id', models.AutoField(primary_key=True, serialize=False)),
                ('g218_opciones', models.CharField(max_length=60)),
                ('g218_estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'j218_opciones',
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('g221_id', models.AutoField(primary_key=True, serialize=False)),
                ('g221_operador', models.CharField(max_length=100)),
                ('g221_estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'j221_operador',
            },
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('g209_id', models.AutoField(primary_key=True, serialize=False)),
                ('g209_procesador', models.CharField(max_length=150)),
                ('g209_estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'j209_procesador',
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('g203_id', models.AutoField(primary_key=True, serialize=False)),
                ('g203_documento', models.CharField(max_length=20)),
                ('g203_propietario', models.CharField(max_length=100)),
                ('g203_estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'j203_propietario',
            },
        ),
        migrations.CreateModel(
            name='SistemaOperativo',
            fields=[
                ('g210_id', models.AutoField(primary_key=True, serialize=False)),
                ('g210_so', models.CharField(max_length=100)),
                ('g210_estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'j210_sistemaoperativo',
            },
        ),
        migrations.CreateModel(
            name='TipoDispositivo',
            fields=[
                ('g200_id', models.AutoField(primary_key=True, serialize=False)),
                ('g200_tipo_dispositivo', models.CharField(max_length=100)),
                ('g200_estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'j200_tipodispositivo',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('g206_id', models.AutoField(primary_key=True, serialize=False)),
                ('g206_tipo_documento', models.CharField(max_length=60)),
                ('g206_estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'j206_tipodocumento',
            },
        ),
        migrations.CreateModel(
            name='TipoNovedad',
            fields=[
                ('g220_id', models.AutoField(primary_key=True, serialize=False)),
                ('g220_novedad', models.CharField(max_length=100)),
                ('g220_estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'j220_tiponovedad',
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('g215_id', models.AutoField(primary_key=True, serialize=False)),
                ('g215_documento', models.CharField(max_length=20, unique=True)),
                ('g215_nombre', models.CharField(max_length=200)),
                ('g215_cargo', models.CharField(max_length=150)),
                ('g215_acc_cargador', models.CharField(default='NO APLICA', max_length=100)),
                ('g215_acc_teclado', models.CharField(default='NO APLICA', max_length=100)),
                ('g215_acc_mouse', models.CharField(default='NO APLICA', max_length=100)),
                ('g215_acc_mousepad', models.CharField(default='NO APLICA', max_length=100)),
                ('g215_acc_diadema', models.CharField(default='NO APLICA', max_length=100)),
                ('g215_acc_base', models.CharField(default='NO APLICA', max_length=100)),
                ('g215_fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('g215_co', models.ForeignKey(blank=True, db_column='g215_co_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.centrocosto')),
                ('g215_estado', models.ForeignKey(db_column='g215_estado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.estado')),
                ('g215_tipo_doc', models.ForeignKey(db_column='g215_tipodoc_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.tipodocumento')),
            ],
            options={
                'db_table': 'j215_colaborador',
            },
        ),
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('g217_id', models.AutoField(primary_key=True, serialize=False)),
                ('g217_tipo', models.CharField(max_length=20)),
                ('g217_proceso', models.CharField(max_length=50)),
                ('g217_correo', models.EmailField(max_length=254)),
                ('g217_firma_recibe', models.TextField(blank=True, null=True)),
                ('g217_firma_entrega', models.TextField(blank=True, null=True)),
                ('g217_fecha', models.DateTimeField(auto_now_add=True)),
                ('g217_colaborador', models.ForeignKey(db_column='g217_colaborador_id', on_delete=django.db.models.deletion.CASCADE, related_name='actas', to='dashboard.colaborador')),
            ],
            options={
                'db_table': 'j217_acta',
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('g212_id', models.AutoField(primary_key=True, serialize=False)),
                ('g212_serial', models.CharField(max_length=50, unique=True)),
                ('g212_modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('g212_anio', models.IntegerField(blank=True, null=True)),
                ('g212_color', models.CharField(blank=True, max_length=50, null=True)),
                ('g212_nombre_equipo', models.CharField(blank=True, max_length=100, null=True)),
                ('g212_valor_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('g212_valor_arrendamiento', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('g212_observaciones', models.TextField(blank=True, null=True)),
                ('g212_fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('g212_co', models.ForeignKey(blank=True, db_column='g212_co_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.centrocosto')),
                ('g212_departamento', models.ForeignKey(blank=True, db_column='g212_departamento_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.departamento')),
                ('g212_estado', models.ForeignKey(db_column='g212_estado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.estado')),
                ('g212_marca', models.ForeignKey(blank=True, db_column='g212_marca_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.marca')),
            ],
            options={
                'db_table': 'j212_dispositivo',
            },
        ),
        migrations.CreateModel(
            name='CaracteristicaPeriferico',
            fields=[
                ('g226_id', models.AutoField(primary_key=True, serialize=False)),
                ('g226_incluye_base', models.BooleanField(default=False)),
                ('g226_incluye_teclado', models.BooleanField(default=False)),
                ('g226_incluye_mouse', models.BooleanField(default=False)),
                ('g226_incluye_auriculares', models.BooleanField(default=False)),
                ('g226_incluye_cargador', models.BooleanField(default=False)),
                ('g226_descripcion_adicional', models.TextField(blank=True, null=True)),
                ('g226_dispositivo', models.OneToOneField(db_column='g226_dispositivo_id', on_delete=django.db.models.deletion.CASCADE, related_name='caract_periferico', to='dashboard.dispositivo')),
            ],
            options={
                'db_table': 'j226_caract_periferico',
            },
        ),
        migrations.CreateModel(
            name='CaracteristicaPantalla',
            fields=[
                ('g224_id', models.AutoField(primary_key=True, serialize=False)),
                ('g224_pulgadas', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('g224_resolucion', models.CharField(blank=True, max_length=50, null=True)),
                ('g224_dispositivo', models.OneToOneField(db_column='g224_dispositivo_id', on_delete=django.db.models.deletion.CASCADE, related_name='caract_pantalla', to='dashboard.dispositivo')),
            ],
            options={
                'db_table': 'j224_caract_pantalla',
            },
        ),
        migrations.CreateModel(
            name='CaracteristicaLicencia',
            fields=[
                ('g227_id', models.AutoField(primary_key=True, serialize=False)),
                ('g227_software', models.CharField(blank=True, max_length=150, null=True)),
                ('g227_version', models.CharField(blank=True, max_length=50, null=True)),
                ('g227_key', models.CharField(blank=True, max_length=150, null=True)),
                ('g227_correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('g227_fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('g227_dispositivo', models.OneToOneField(db_column='g227_dispositivo_id', on_delete=django.db.models.deletion.CASCADE, related_name='caract_licencia', to='dashboard.dispositivo')),
            ],
            options={
                'db_table': 'j227_caract_licencia',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('g205_id', models.AutoField(primary_key=True, serialize=False)),
                ('g205_municipio', models.CharField(max_length=100)),
                ('g205_estado', models.BooleanField(default=True)),
                ('g205_departamento', models.ForeignKey(db_column='g205_departamento_id', on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='dashboard.departamento')),
            ],
            options={
                'db_table': 'j205_municipio',
            },
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='g212_municipio',
            field=models.ForeignKey(blank=True, db_column='g212_municipio_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.municipio'),
        ),
        migrations.CreateModel(
            name='CaracteristicaImpresora',
            fields=[
                ('g225_id', models.AutoField(primary_key=True, serialize=False)),
                ('g225_funcion', models.CharField(blank=True, max_length=100, null=True)),
                ('g225_dispositivo', models.OneToOneField(db_column='g225_dispositivo_id', on_delete=django.db.models.deletion.CASCADE, related_name='caract_impresora', to='dashboard.dispositivo')),
                ('g225_tipo_impresora', models.ForeignKey(blank=True, db_column='g225_tipo_impresora_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impresoras_tipo', to='dashboard.opciones')),
            ],
            options={
                'db_table': 'j225_caract_impresora',
            },
        ),
        migrations.CreateModel(
            name='CaracteristicaMovil',
            fields=[
                ('g223_id', models.AutoField(primary_key=True, serialize=False)),
                ('g223_numero_linea', models.CharField(blank=True, max_length=20, null=True)),
                ('g223_plan_datos', models.CharField(blank=True, max_length=100, null=True)),
                ('g223_imei1', models.CharField(blank=True, max_length=20, null=True)),
                ('g223_imei2', models.CharField(blank=True, max_length=20, null=True)),
                ('g223_cuenta_gmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('g223_contrasena_gmail', models.CharField(blank=True, max_length=100, null=True)),
                ('g223_pulgadas', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('g223_almacenamiento', models.ForeignKey(blank=True, db_column='g223_almacenamiento_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.almacenamiento')),
                ('g223_dispositivo', models.OneToOneField(db_column='g223_dispositivo_id', on_delete=django.db.models.deletion.CASCADE, related_name='caract_movil', to='dashboard.dispositivo')),
                ('g223_operador', models.ForeignKey(blank=True, db_column='g223_operador_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.operador')),
            ],
            options={
                'db_table': 'j223_caract_movil',
            },
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='g212_propietario',
            field=models.ForeignKey(db_column='g212_propietario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.propietario'),
        ),
        migrations.CreateModel(
            name='CaracteristicaPC',
            fields=[
                ('g222_id', models.AutoField(primary_key=True, serialize=False)),
                ('g222_correo_office', models.EmailField(blank=True, max_length=254, null=True)),
                ('g222_key_office', models.CharField(blank=True, max_length=150, null=True)),
                ('g222_activo', models.CharField(blank=True, max_length=100, null=True)),
                ('g222_pulgadas', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('g222_almacenamiento', models.ForeignKey(blank=True, db_column='g222_almacenamiento_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.almacenamiento')),
                ('g222_antivirus', models.ForeignKey(blank=True, db_column='g222_antivirus_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.antivirus')),
                ('g222_dispositivo', models.OneToOneField(db_column='g222_dispositivo_id', on_delete=django.db.models.deletion.CASCADE, related_name='caract_pc', to='dashboard.dispositivo')),
                ('g222_licencia', models.ForeignKey(blank=True, db_column='g222_licencia_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.licenciaoffice')),
                ('g222_ram', models.ForeignKey(blank=True, db_column='g222_ram_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pcs_ram', to='dashboard.opciones')),
                ('g222_tipo_disco', models.ForeignKey(blank=True, db_column='g222_tipodisco_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pcs_tipodisco', to='dashboard.opciones')),
                ('g222_procesador', models.ForeignKey(blank=True, db_column='g222_procesador_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.procesador')),
                ('g222_so', models.ForeignKey(blank=True, db_column='g222_so_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.sistemaoperativo')),
            ],
            options={
                'db_table': 'j222_caract_pc',
            },
        ),
        migrations.CreateModel(
            name='DispositivoInactivo',
            fields=[
                ('g213_id', models.AutoField(primary_key=True, serialize=False)),
                ('g213_serial', models.CharField(blank=True, max_length=50, null=True)),
                ('g213_modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('g213_observaciones', models.TextField(blank=True, null=True)),
                ('g213_fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('g213_co', models.ForeignKey(blank=True, db_column='g213_co_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.centrocosto')),
                ('g213_estado', models.ForeignKey(db_column='g213_estado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.estado')),
                ('g213_marca', models.ForeignKey(blank=True, db_column='g213_marca_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.marca')),
                ('g213_propietario', models.ForeignKey(db_column='g213_propietario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.propietario')),
                ('g213_tipo', models.ForeignKey(db_column='g213_tipo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.tipodispositivo')),
            ],
            options={
                'db_table': 'j213_dispositivoinactivo',
            },
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='g212_tipo',
            field=models.ForeignKey(db_column='g212_tipo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='dashboard.tipodispositivo'),
        ),
        migrations.AddField(
            model_name='propietario',
            name='g203_id_tipo_documento',
            field=models.ForeignKey(db_column='g203_id_tipo_documento', on_delete=django.db.models.deletion.PROTECT, to='dashboard.tipodocumento'),
        ),
        migrations.CreateModel(
            name='HistorialEquipo',
            fields=[
                ('g214_id', models.AutoField(primary_key=True, serialize=False)),
                ('g214_fecha', models.DateField()),
                ('g214_hora', models.TimeField()),
                ('g214_responsable', models.CharField(max_length=150)),
                ('g214_observaciones', models.TextField(blank=True, null=True)),
                ('g214_fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('g214_co', models.ForeignKey(blank=True, db_column='g214_co_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.centrocosto')),
                ('g214_dispositivo', models.ForeignKey(db_column='g214_dispositivo_id', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='dashboard.dispositivo')),
                ('g214_novedad', models.ForeignKey(db_column='g214_novedad_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.tiponovedad')),
            ],
            options={
                'db_table': 'j214_historialequipo',
            },
        ),
        migrations.CreateModel(
            name='AsignacionColaborador',
            fields=[
                ('g216_id', models.AutoField(primary_key=True, serialize=False)),
                ('g216_fecha', models.DateTimeField(auto_now_add=True)),
                ('g216_colaborador', models.ForeignKey(db_column='g216_colaborador_id', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='dashboard.colaborador')),
                ('g216_dispositivo', models.ForeignKey(db_column='g216_dispositivo_id', on_delete=django.db.models.deletion.CASCADE, to='dashboard.dispositivo')),
            ],
            options={
                'db_table': 'j216_asignacion',
                'unique_together': {('g216_colaborador', 'g216_dispositivo')},
            },
        ),
    ]
