# Generated by Django 6.0.4 on 2026-05-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='g215_acc_base',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='g215_acc_cargador',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='g215_acc_diadema',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='g215_acc_mouse',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='g215_acc_mousepad',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='g215_acc_teclado',
        ),
    ]
