# Generated by Django 6.0.4 on 2026-05-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_colaborador_g215_acc_base_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='g215_tipo_doc',
        ),
    ]
