# Generated by Django 6.0.4 on 2026-05-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_colaborador_g215_tipo_doc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CentroCosto',
            new_name='CentroOperaciones',
        ),
        migrations.AlterModelTable(
            name='centrooperaciones',
            table='CentroOperaciones',
        ),
    ]
