# Generated by Django 6.0.4 on 2026-05-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_centrocosto_centrooperaciones_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='centrooperaciones',
            table='j207_CentroOperaciones',
        ),
    ]
