# Generated by Django 6.0.4 on 2026-05-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_centrooperaciones_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centrooperaciones',
            name='g207_estado',
        ),
    ]
