# Generated by Django 6.0.4 on 2026-05-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_centrooperaciones_g207_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrooperaciones',
            name='g207_estado',
            field=models.BooleanField(default=True),
        ),
    ]
