# Generated by Django 6.0.4 on 2026-05-26 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_centrooperaciones_g207_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio',
            name='g205_departamento',
        ),
    ]
