# Generated by Django 6.0.4 on 2026-05-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_municipio_g205_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='g205_latitud',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='g205_longitud',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
