# Generated by Django 6.0.4 on 2026-05-26 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_municipio_g205_latitud_municipio_g205_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='g205_departamento',
            field=models.ForeignKey(blank=True, db_column='g205_id_departamento', null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.departamento'),
        ),
    ]
