# Generated by Django 6.0.4 on 2026-05-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_municipio_g205_departamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipio',
            old_name='g205_departamento',
            new_name='g205_id_departamento',
        ),
    ]
