# Generated by Django 6.0.4 on 2026-05-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rename_g205_departamento_municipio_g205_id_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='g205_latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='g205_longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
