# Generated by Django 6.0.4 on 2026-05-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_municipio_g205_latitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='g205_latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='g205_longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
