# Generated by Django 6.0.4 on 2026-05-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_municipio_g205_latitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='g205_latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='g205_longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
