# Generated by Django 6.0.4 on 2026-05-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_municipio_g205_latitud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('g228_id', models.AutoField(primary_key=True, serialize=False)),
                ('g228_nombre', models.CharField(max_length=100)),
                ('g228_estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Centro de Costo',
                'db_table': 'g228_centro_costo',
            },
        ),
        migrations.RenameField(
            model_name='municipio',
            old_name='g205_id_departamento',
            new_name='g205_departamento',
        ),
    ]
