# Generated by Django 6.0.4 on 2026-05-29 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_dispositivo_g212_centro_costo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoImpresora',
            fields=[
                ('g229_id', models.AutoField(primary_key=True, serialize=False)),
                ('g229_tipo_impresora', models.CharField(max_length=100)),
                ('g229_estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Impresora',
                'db_table': 'j229_tipoimpresora',
            },
        ),
        migrations.AlterField(
            model_name='caracteristicaimpresora',
            name='g225_tipo_impresora',
            field=models.ForeignKey(blank=True, db_column='g225_tipo_impresora_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impresoras', to='dashboard.tipoimpresora'),
        ),
    ]
