# Generated by Django 6.0.4 on 2026-05-30 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_tipoimpresora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('g230_id', models.AutoField(primary_key=True, serialize=False)),
                ('g230_ram', models.CharField(max_length=50)),
                ('g230_estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'RAM',
                'db_table': 'j230_ram',
            },
        ),
        migrations.CreateModel(
            name='TipoDisco',
            fields=[
                ('g231_id', models.AutoField(primary_key=True, serialize=False)),
                ('g231_tipo_disco', models.CharField(max_length=50)),
                ('g231_estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Disco',
                'db_table': 'j231_tipo_disco',
            },
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='g212_ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caracteristicapc',
            name='g222_ram',
            field=models.ForeignKey(blank=True, db_column='g222_ram_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pcs_ram', to='dashboard.ram'),
        ),
        migrations.AlterField(
            model_name='caracteristicapc',
            name='g222_tipo_disco',
            field=models.ForeignKey(blank=True, db_column='g222_tipodisco_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pcs_tipodisco', to='dashboard.tipodisco'),
        ),
    ]
