# Generated by Django 6.0.4 on 2026-05-31 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_ram_tipodisco_dispositivo_g212_ubicacion_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='centrocosto',
            table='j228_centroCosto',
        ),
    ]
