# Generated by Django 6.0.4 on 2026-06-01 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_centrocosto_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='g212_anio',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='g212_color',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='g212_modelo',
        ),
    ]
