# Generated by Django 6.0.4 on 2026-06-03 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_remove_modelo_anio_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicasVideoBeam',
            fields=[
                ('g232_id', models.AutoField(primary_key=True, serialize=False)),
                ('g232_lumenes', models.IntegerField(blank=True, null=True)),
                ('g232_dispositivo', models.OneToOneField(db_column='g232_dispositivo_id', on_delete=django.db.models.deletion.CASCADE, related_name='caract_videobeam', to='dashboard.dispositivo')),
            ],
            options={
                'db_table': 'j232_caract_videobeam',
            },
        ),
    ]
