# Generated by Django 6.0.4 on 2026-06-04 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_caracteristicasvideobeam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialequipo',
            name='g214_novedad',
        ),
        migrations.AddField(
            model_name='historialequipo',
            name='g214_estado',
            field=models.ForeignKey(db_column='g214_estado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.estado'),
        ),
    ]
