# Generated by Django 6.0.4 on 2026-06-04 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_remove_historialequipo_g214_novedad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialequipo',
            name='g214_estado',
        ),
        migrations.AddField(
            model_name='historialequipo',
            name='g214_novedad',
            field=models.ForeignKey(db_column='g214_novedad_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.tiponovedad'),
        ),
    ]
