# Generated by Django 6.0.4 on 2026-06-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_remove_historialequipo_g214_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicapc',
            name='g222_ram',
            field=models.IntegerField(blank=True, db_column='g222_ram', null=True),
        ),
    ]
