# Generated by Django 6.0.4 on 2026-06-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_caracteristicapc_g222_ram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centrocosto',
            options={'verbose_name': 'Area'},
        ),
        migrations.AlterModelTable(
            name='centrocosto',
            table='j228_Area',
        ),
    ]
