# Generated by Django 6.0.4 on 2026-06-10 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_centrocosto_options_alter_centrocosto_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='g215_Area',
            field=models.ForeignKey(blank=True, db_column='g215_area_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.centrocosto'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='g215_correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
