# Generated by Django 6.0.6 on 2026-08-04 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0026_colaborador_g215_area_colaborador_g215_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'core_modulo',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='OpcionMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('screen_key', models.SlugField(help_text='Debe coincidir con el data-screen del HTML', max_length=60, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opciones', to='dashboard.modulo')),
            ],
            options={
                'db_table': 'core_opcionmenu',
                'ordering': ['modulo__orden', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='OpcionMenuGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solo_lectura', models.BooleanField(default=False)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.opcionmenu')),
            ],
            options={
                'verbose_name': 'Acceso de grupo a opción de menú',
                'verbose_name_plural': 'Accesos de grupo a opciones de menú',
                'db_table': 'core_opcionmenugrupo',
                'unique_together': {('opcion', 'grupo')},
            },
        ),
        migrations.AddField(
            model_name='opcionmenu',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='opciones_menu', through='dashboard.OpcionMenuGrupo', to='auth.group'),
        ),
    ]
