# Generated by Django 6.0.6 on 2026-08-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_modulo_opcionmenu_opcionmenugrupo_opcionmenu_grupos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicapc',
            name='g222_ram',
            field=models.CharField(blank=True, db_column='g222_ram', max_length=20, null=True),
        ),
    ]
