# Generated by Django 6.0.6 on 2026-08-10 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_tipoacta'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristicalicencia',
            name='g227_almacenamiento',
            field=models.ForeignKey(blank=True, db_column='g227_almacenamiento_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.almacenamiento'),
        ),
    ]
