# Generated by Django 6.0.6 on 2026-08-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_caracteristicalicencia_g227_almacenamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicapc',
            name='g222_ram',
            field=models.IntegerField(blank=True, db_column='g222_ram', null=True),
        ),
    ]
