# Generated by Django 6.0.6 on 2026-08-18 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_caracteristicapc_g222_ram'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaDispositivo',
            fields=[
                ('g234_id', models.AutoField(primary_key=True, serialize=False)),
                ('g234_acta', models.ForeignKey(db_column='g234_acta_id', on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_acta', to='dashboard.acta')),
                ('g234_dispositivo', models.ForeignKey(db_column='g234_dispositivo_id', on_delete=django.db.models.deletion.CASCADE, to='dashboard.dispositivo')),
            ],
            options={
                'db_table': 'j234_acta_dispositivo',
                'unique_together': {('g234_acta', 'g234_dispositivo')},
            },
        ),
    ]
