# Generated by Django 6.0.6 on 2026-08-21 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_actadispositivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialequipo',
            name='g214_dispositivo_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historialequipo',
            name='g214_dispositivo',
            field=models.ForeignKey(db_column='g214_dispositivo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='dashboard.dispositivo'),
        ),
    ]
