# Generated by Django 6.0.6 on 2026-08-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_historialequipo_g214_dispositivo_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionBellLeida',
            fields=[
                ('g235_id', models.AutoField(primary_key=True, serialize=False)),
                ('g235_usuario_id', models.IntegerField()),
                ('g235_tipo', models.CharField(max_length=20)),
                ('g235_referencia_id', models.IntegerField()),
                ('g235_referencia_fecha', models.CharField(max_length=20)),
                ('g235_fecha_marcado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'j235_notificacion_bell_leida',
                'unique_together': {('g235_usuario_id', 'g235_tipo', 'g235_referencia_id', 'g235_referencia_fecha')},
            },
        ),
    ]
