# Generated by Django 6.0.6 on 2026-08-25 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_notificacionbellleida'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemChecklist',
            fields=[
                ('g236_id', models.AutoField(primary_key=True, serialize=False)),
                ('g236_pregunta', models.CharField(max_length=200)),
                ('g236_estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pregunta de Checklist',
                'verbose_name_plural': 'Preguntas de Checklist',
                'db_table': 'j236_item_checklist',
            },
        ),
        migrations.CreateModel(
            name='ChecklistDispositivo',
            fields=[
                ('g237_id', models.AutoField(primary_key=True, serialize=False)),
                ('g237_dispositivo_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('g237_responsable', models.CharField(max_length=150)),
                ('g237_observaciones', models.TextField(blank=True, null=True)),
                ('g237_firma', models.TextField(blank=True, null=True)),
                ('g237_fecha', models.DateTimeField(auto_now_add=True)),
                ('g237_dispositivo', models.ForeignKey(db_column='g237_dispositivo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='dashboard.dispositivo')),
            ],
            options={
                'verbose_name': 'Checklist de Dispositivo',
                'verbose_name_plural': 'Checklists de Dispositivo',
                'db_table': 'j237_checklist_dispositivo',
            },
        ),
        migrations.CreateModel(
            name='RespuestaChecklist',
            fields=[
                ('g238_id', models.AutoField(primary_key=True, serialize=False)),
                ('g238_item_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('g238_respuesta', models.BooleanField()),
                ('g238_checklist', models.ForeignKey(db_column='g238_checklist_id', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='dashboard.checklistdispositivo')),
                ('g238_item', models.ForeignKey(db_column='g238_item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.itemchecklist')),
            ],
            options={
                'verbose_name': 'Respuesta de Checklist',
                'verbose_name_plural': 'Respuestas de Checklist',
                'db_table': 'j238_respuesta_checklist',
            },
        ),
    ]
