# Generated by Django 6.0.6 on 2026-08-25 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_itemchecklist_checklistdispositivo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemchecklist',
            options={'ordering': ['g236_seccion', 'g236_orden', 'g236_id'], 'verbose_name': 'Pregunta de Checklist', 'verbose_name_plural': 'Preguntas de Checklist'},
        ),
        migrations.AddField(
            model_name='itemchecklist',
            name='g236_orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemchecklist',
            name='g236_seccion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='itemchecklist',
            name='g236_tipo_dispositivo',
            field=models.ForeignKey(blank=True, db_column='g236_tipo_dispositivo_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.tipodispositivo'),
        ),
    ]
