# Generated by Django 6.0.6 on 2026-08-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_alter_itemchecklist_options_itemchecklist_g236_orden_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemchecklist',
            options={'ordering': ['g236_orden', 'g236_id'], 'verbose_name': 'Pregunta de Checklist', 'verbose_name_plural': 'Preguntas de Checklist'},
        ),
    ]
