# Generated by Django 6.0.6 on 2026-08-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_alter_itemchecklist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemchecklist',
            name='g236_es_texto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='respuestachecklist',
            name='g238_valor_texto',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='respuestachecklist',
            name='g238_respuesta',
            field=models.BooleanField(default=False),
        ),
    ]
