# Generated by Django 6.0.6 on 2026-08-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_itemchecklist_g236_es_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistdispositivo',
            name='g237_resp_area',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='checklistdispositivo',
            name='g237_resp_cargo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='checklistdispositivo',
            name='g237_resp_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
