# Generated by Django 6.0.6 on 2026-08-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_checklistdispositivo_g237_resp_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistdispositivo',
            name='g237_resp_cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
