# Generated by Django 6.0.6 on 2026-08-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_checklistdispositivo_g237_resp_cedula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistdispositivo',
            name='g237_firma',
        ),
    ]
