# Generated by Django 6.0.6 on 2026-08-26 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_remove_checklist_firma'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoNovedadGeneral',
            fields=[
                ('g240_id', models.AutoField(primary_key=True, serialize=False)),
                ('g240_nombre_campo', models.CharField(max_length=150)),
                ('g240_orden', models.PositiveIntegerField(default=0)),
                ('g240_estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Campo de Novedad General',
                'verbose_name_plural': 'Campos de Novedad General',
                'db_table': 'j240_campo_novedad_general',
                'ordering': ['g240_orden', 'g240_id'],
            },
        ),
        migrations.CreateModel(
            name='NovedadGeneral',
            fields=[
                ('g241_id', models.AutoField(primary_key=True, serialize=False)),
                ('g241_tipo_desc', models.CharField(blank=True, max_length=150, null=True)),
                ('g241_responsable', models.CharField(max_length=150)),
                ('g241_observaciones', models.TextField(blank=True, null=True)),
                ('g241_fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Novedad General',
                'verbose_name_plural': 'Novedades Generales',
                'db_table': 'j241_novedad_general',
                'ordering': ['-g241_fecha'],
            },
        ),
        migrations.CreateModel(
            name='TipoNovedadGeneral',
            fields=[
                ('g239_id', models.AutoField(primary_key=True, serialize=False)),
                ('g239_nombre', models.CharField(max_length=150)),
                ('g239_estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Novedad General',
                'verbose_name_plural': 'Tipos de Novedad General',
                'db_table': 'j239_tipo_novedad_general',
                'ordering': ['g239_nombre'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaNovedadGeneral',
            fields=[
                ('g242_id', models.AutoField(primary_key=True, serialize=False)),
                ('g242_campo_desc', models.CharField(blank=True, max_length=150, null=True)),
                ('g242_observacion', models.TextField(blank=True, null=True)),
                ('g242_campo', models.ForeignKey(db_column='g242_campo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.camponovedadgeneral')),
                ('g242_novedad', models.ForeignKey(db_column='g242_novedad_id', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='dashboard.novedadgeneral')),
            ],
            options={
                'verbose_name': 'Respuesta de Novedad General',
                'verbose_name_plural': 'Respuestas de Novedad General',
                'db_table': 'j242_respuesta_novedad_general',
            },
        ),
        migrations.AddField(
            model_name='novedadgeneral',
            name='g241_tipo',
            field=models.ForeignKey(db_column='g241_tipo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades', to='dashboard.tiponovedadgeneral'),
        ),
        migrations.AddField(
            model_name='camponovedadgeneral',
            name='g240_tipo_novedad',
            field=models.ForeignKey(db_column='g240_tipo_novedad_id', on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='dashboard.tiponovedadgeneral'),
        ),
    ]
