# Generated by Django 6.0.6 on 2026-08-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_novedades_generales'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistdispositivo',
            name='g237_fecha_edicion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
