# Generated by Django 6.0.6 on 2026-08-28 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_checklist_fecha_edicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoNovedadGeneral',
            fields=[
                ('g243_id', models.AutoField(primary_key=True, serialize=False)),
                ('g243_nombre', models.CharField(max_length=255)),
                ('g243_fecha', models.DateTimeField(auto_now_add=True)),
                ('g243_novedad', models.ForeignKey(db_column='g243_novedad_id', on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='dashboard.novedadgeneral')),
            ],
            options={
                'verbose_name': 'Adjunto de Novedad General',
                'verbose_name_plural': 'Adjuntos de Novedad General',
                'db_table': 'j243_adjunto_novedad_general',
            },
        ),
    ]
