# Generated by Django 6.0.6 on 2026-08-12 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('IdArea', models.AutoField(primary_key=True, serialize=False)),
                ('NombreArea', models.CharField(max_length=150)),
                ('CorreoJefe', models.EmailField(max_length=200)),
                ('Estado', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'db_table': 'mm_Area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('IdCargo', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=200)),
                ('Estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'mm_Cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('IdCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=200)),
                ('IdRequerimiento', models.IntegerField(blank=True, null=True)),
                ('TiempoDias', models.IntegerField(blank=True, null=True)),
                ('Estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'mm_Categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CentroOperacion',
            fields=[
                ('IdCo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=200)),
                ('Zona', models.CharField(blank=True, max_length=100, null=True)),
                ('Ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('Estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mm_CentroOperacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('IdClasificacion', models.AutoField(primary_key=True, serialize=False)),
                ('Clasificacion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'mm_Clasificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('IdEquipo', models.AutoField(primary_key=True, serialize=False)),
                ('NombreEquipo', models.CharField(max_length=150)),
                ('Descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('IdResponsable', models.IntegerField(blank=True, null=True)),
                ('IdEstado', models.IntegerField()),
            ],
            options={
                'db_table': 'mv_Equipos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoGeneral',
            fields=[
                ('IdEstado', models.AutoField(db_column='f100_id', primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(db_column='f100_descripcion', max_length=100)),
            ],
            options={
                'db_table': 't100_mm_estados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoRequerimiento',
            fields=[
                ('IdEstado', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mm_EstadoRequerimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluacionReq',
            fields=[
                ('IdEvaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('IdReq', models.IntegerField()),
                ('Evaluacion', models.IntegerField(blank=True, null=True)),
                ('Comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mv_EvaluacionReq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialPrestamo',
            fields=[
                ('IdPrestamo', models.AutoField(primary_key=True, serialize=False)),
                ('Cedula', models.CharField(max_length=20)),
                ('NombreSolicitante', models.CharField(max_length=150)),
                ('Area', models.CharField(blank=True, max_length=150, null=True)),
                ('FechaPrestamo', models.DateTimeField(auto_now_add=True)),
                ('FechaEstimadaDevolucion', models.DateField(blank=True, null=True)),
                ('FechaDevolucionReal', models.DateTimeField(blank=True, null=True)),
                ('Observaciones', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'mv_HistorialPrestamos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagenAdjunta',
            fields=[
                ('IdImagen', models.AutoField(primary_key=True, serialize=False)),
                ('CodReq', models.IntegerField()),
                ('NombreImagen', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'mm_ImagenesAdjuntos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('IdNotificacion', models.AutoField(primary_key=True, serialize=False)),
                ('CedulaUsuario', models.CharField(max_length=20)),
                ('Tipo', models.CharField(max_length=30)),
                ('Codigo', models.IntegerField(blank=True, null=True)),
                ('Titulo', models.CharField(max_length=200)),
                ('Mensaje', models.CharField(max_length=500)),
                ('Leida', models.BooleanField(default=False)),
                ('FechaCreacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mv_Notificaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('IdPrioridad', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Porcentaje', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mm_Prioridad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('Codigo', models.AutoField(primary_key=True, serialize=False)),
                ('IdJefeArea', models.IntegerField(blank=True, null=True)),
                ('Fecha', models.DateField(blank=True, null=True)),
                ('IdUsuario', models.IntegerField(blank=True, null=True)),
                ('CedulaUsuario', models.IntegerField(blank=True, null=True)),
                ('NombreUsuario', models.CharField(blank=True, max_length=150, null=True)),
                ('Cargo', models.IntegerField(blank=True, null=True)),
                ('CO', models.CharField(blank=True, max_length=100, null=True)),
                ('Equipo', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('IdTipoReq', models.IntegerField(blank=True, null=True)),
                ('Requerimiento', models.TextField(blank=True, null=True)),
                ('IdPrioridad', models.IntegerField(blank=True, null=True)),
                ('IdUsuarioAsig', models.IntegerField(blank=True, db_column='IdUsuarioAsignado', null=True)),
                ('NombreUsuariAsig', models.CharField(blank=True, db_column='NombreUsuarioAsignado', max_length=150, null=True)),
                ('IdTipoSolicitud', models.IntegerField(blank=True, null=True)),
                ('IdParteAfectada', models.IntegerField(blank=True, null=True)),
                ('IdCategoria', models.IntegerField(blank=True, null=True)),
                ('IdSubCategoria', models.IntegerField(blank=True, null=True)),
                ('IdEstado', models.IntegerField(blank=True, null=True)),
                ('FechaEstiSoluci', models.DateField(blank=True, db_column='FechaEstiSolucion', null=True)),
                ('PlanAccion', models.TextField(blank=True, null=True)),
                ('FechaRealSoluci', models.DateField(blank=True, db_column='FechaRealSolucion', null=True)),
                ('Solucion', models.TextField(blank=True, null=True)),
                ('Clasificacion', models.IntegerField(blank=True, null=True)),
                ('Costo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('TokenAprobacion', models.CharField(blank=True, max_length=64, null=True)),
                ('FechaAprobacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mv_Requerimientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('IdSubCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=200)),
                ('IdCategoria', models.IntegerField()),
                ('TiempoDias', models.IntegerField(blank=True, null=True)),
                ('Prioridad', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'mm_SubCategoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoRequerimiento',
            fields=[
                ('IdTipoReque', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'mm_TipoRequerimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idTipoUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mm_TipoUsuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('IdUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('Cedula', models.CharField(max_length=20, unique=True)),
                ('NombreCompleto', models.CharField(max_length=150)),
                ('IdCargo', models.IntegerField(blank=True, null=True)),
                ('IdArea', models.IntegerField(blank=True, null=True)),
                ('IdCO', models.CharField(max_length=50)),
                ('Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('Contrasena', models.CharField(blank=True, db_column='Contraseña', max_length=255, null=True)),
                ('FechaCreacion', models.DateTimeField(blank=True, null=True)),
                ('TipoUsuario', models.IntegerField(blank=True, null=True)),
                ('Estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mv_Usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('IdChat', models.AutoField(primary_key=True, serialize=False)),
                ('IdUsuario', models.IntegerField(db_index=True, unique=True)),
                ('Cedula', models.CharField(db_index=True, max_length=20)),
                ('GraphChatId', models.CharField(max_length=200)),
                ('CorreoAgente', models.EmailField(max_length=200)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('UltimaActividad', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chat_hilo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChatMicrosoftToken',
            fields=[
                ('IdVinculacion', models.AutoField(primary_key=True, serialize=False)),
                ('IdUsuario', models.IntegerField(db_index=True, unique=True)),
                ('Cedula', models.CharField(db_index=True, max_length=20)),
                ('AadObjectId', models.CharField(blank=True, max_length=64, null=True)),
                ('Upn', models.CharField(blank=True, max_length=200, null=True)),
                ('MsalTokenCache', models.BinaryField(blank=True, max_length='max', null=True)),
                ('FechaVinculacion', models.DateTimeField(auto_now_add=True)),
                ('FechaUltimoUso', models.DateTimeField(blank=True, null=True)),
                ('Activo', models.BooleanField(default=True)),
                ('UltimoError', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'chat_ms_token',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('IdMensaje', models.AutoField(primary_key=True, serialize=False)),
                ('GraphMessageId', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('Direccion', models.CharField(choices=[('SALIENTE', 'Saliente'), ('ENTRANTE', 'Entrante')], max_length=10)),
                ('Texto', models.TextField()),
                ('FechaGraph', models.DateTimeField(blank=True, null=True)),
                ('FechaLocal', models.DateTimeField(auto_now_add=True)),
                ('Leido', models.BooleanField(default=False)),
                ('Estado', models.CharField(choices=[('enviado', 'Enviado'), ('error', 'Error de envío')], default='enviado', max_length=20)),
                ('IdChat', models.ForeignKey(db_column='IdChat', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='requerimientos.chat')),
            ],
            options={
                'db_table': 'chat_mensaje',
                'managed': True,
                'indexes': [models.Index(fields=['IdChat', 'FechaGraph'], name='chat_mensaj_IdChat_6efa57_idx')],
            },
        ),
    ]
